### ISSUE TITLE
Bold and Italics

### ISSUE THREAD

**Issue by vvizard-** [imintinvestors/imintinvestors.com#29]
A _single underscore_ should probably make text italic? while a __double underscore__ should make it bold?

Now a single underscore make things bold, while double underscores make things bold'er.

**Comment by simonmika** [comment]
I'd rather actually don't have double underscore. The more variant that are allowed the crazier formatted the pages become. It also adds to the load times of the pages as more font variants need to be downloaded.

**Comment by simonmika** [comment]
To me only one way of emphasizing text should be enough.

**Comment by vvizard-** [comment]
Ok
